In [1]:
!pip install psycopg2-binary
try:
    from faker import Faker
except:
   !pip install faker 
   from faker import Faker
    
try:
    import psycopg2 
except:
    !pip install psycopg2-binary 
    import psycopg2
    
try:
    from sqlalchemy import create_engine
except:
    !pip install sqlalchemy
    from sqlalchemy import create_engine
    
    
try:
    import pandas as pd 
except:
    !pip install pandas
    import pandas as pd

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 1.8 MB/s eta 0:00:0000:0100:01
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.3
Collecting faker
  Downloading Faker-13.12.1-py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 2.2 MB/s eta 0:00:0000:0100:010m
Requirement already satisfied: python-dateutil>=2.4 in /opt/conda/lib/python3.9/site-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.9/site-packages (from python-dateutil>=2.4->faker) (1.16.0)
Installing collected packages: faker
Successfully installed faker-13.12.1
Collecting pandas
  Downloading pandas-1.4.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 1.3 MB/s eta 0:00:0000:0100:01m
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/conda/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.9/site-packages (from pandas) (2022.1)
Collecting numpy>=1.18.5
  Downloading numpy-1.22.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 3.9 MB/s eta 0:00:0000:0100:01m
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Installing collected packages: numpy, pandas
Successfully installed numpy-1.22.4 pandas-1.4.2

In [2]:
from sqlalchemy import inspect,create_engine
import psycopg2

host="postgres_storage"
database="csv_db"
user="Huda"
password="1234"
port='5432'
engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{database}')
insp = inspect(engine)
print(insp.get_table_names())

[]

In [3]:
from faker import Faker
import csv
import pandas as pd 
output=open('/home/sharedVol/data.csv','w')
fake=Faker()
header=['name','age','street','city','state','zip','lng','lat']
mywriter=csv.writer(output)
mywriter.writerow(header)
for r in range(100):
    row =[fake.name(),fake.random_int(min=18,max=80, step=1), 
                       fake.street_address(), fake.city(),fake.state(),
                       fake.zipcode(),fake.longitude(),fake.latitude()]
    mywriter.writerow(row)

output.close()

In [4]:
DF=pd.read_csv('/home/sharedVol/data.csv')

DF.head(10)

,name,age,street,city,state,zip,lng,lat
0,Juan Henderson,70,314 Johnston Pine,Lake Elizabethton,Montana,80498,-66.110491,13.908839
1,Christopher Becker,46,171 Michelle Branch Apt. 253,Andrewton,Texas,77027,-85.662816,87.893525
2,Joseph Delgado,77,771 Horne Ferry Suite 787,Mooretown,Idaho,46500,-58.083436,-28.560389
3,Justin Owens,21,242 Nicole Crossroad Apt. 208,East Omar,Missouri,5246,-2.251244,14.322541
4,Robert Harris,73,5945 Cheryl Vista Suite 187,Jasonstad,Nevada,30805,-166.650078,-42.389466
5,Dr. Joseph Stokes PhD,32,04268 Gilbert Vista Suite 277,Ruizberg,Minnesota,17108,66.582027,61.055819
6,Amanda Diaz,55,993 Lee Bypass Suite 744,Lake Angela,New Mexico,78195,-82.284952,-31.967741
7,Jodi Randall,44,52154 William Greens Suite 765,Port Sharonstad,Alabama,49609,-27.807087,28.713707
8,Amber Reid,77,4572 Stein Groves,Kruegerbury,Oregon,44020,-80.733591,-69.899333
9,Michael Webb,32,3197 Gabriela Camp Apt. 179,Harveyside,Nebraska,35633,-72.490793,-10.648772

In [5]:

DF.to_sql('users2021', engine,if_exists='replace',index=False)

100

In [6]:
DF2=pd.read_sql("SELECT * FROM users2021" , engine);
DF2.head(10)

,name,age,street,city,state,zip,lng,lat
0,Juan Henderson,70,314 Johnston Pine,Lake Elizabethton,Montana,80498,-66.110491,13.908839
1,Christopher Becker,46,171 Michelle Branch Apt. 253,Andrewton,Texas,77027,-85.662816,87.893525
2,Joseph Delgado,77,771 Horne Ferry Suite 787,Mooretown,Idaho,46500,-58.083436,-28.560389
3,Justin Owens,21,242 Nicole Crossroad Apt. 208,East Omar,Missouri,5246,-2.251244,14.322541
4,Robert Harris,73,5945 Cheryl Vista Suite 187,Jasonstad,Nevada,30805,-166.650078,-42.389466
5,Dr. Joseph Stokes PhD,32,04268 Gilbert Vista Suite 277,Ruizberg,Minnesota,17108,66.582027,61.055819
6,Amanda Diaz,55,993 Lee Bypass Suite 744,Lake Angela,New Mexico,78195,-82.284952,-31.967741
7,Jodi Randall,44,52154 William Greens Suite 765,Port Sharonstad,Alabama,49609,-27.807087,28.713707
8,Amber Reid,77,4572 Stein Groves,Kruegerbury,Oregon,44020,-80.733591,-69.899333
9,Michael Webb,32,3197 Gabriela Camp Apt. 179,Harveyside,Nebraska,35633,-72.490793,-10.648772

In [7]:
DF2.to_csv("/home/sharedVol/data2.csv")

In [10]:
!pip install pymongo

Collecting pymongo
  Downloading pymongo-4.1.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (471 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 471.3/471.3 kB 1.3 MB/s eta 0:00:0000:0100:01
Installing collected packages: pymongo
Successfully installed pymongo-4.1.1

In [11]:
from pymongo import MongoClient
client = MongoClient('mongo:27017', 
                        username='Huda',
                         password='1234')

In [12]:
db = client['users2021']

In [13]:
collection = db['users']

In [14]:
DF2.reset_index(inplace=True)
data_dict = DF2.to_dict("records")
# Insert collection
collection.insert_many(data_dict)

In [15]:
cursor = collection.find({})
for document in cursor:
    print(document)

{'_id': ObjectId('629e14cacd42703bcd93e03a'), 'index': 0, 'name': 'Juan Henderson', 'age': 70, 'street': '314 Johnston Pine', 'city': 'Lake Elizabethton', 'state': 'Montana', 'zip': 80498, 'lng': -66.110491, 'lat': 13.9088395}
{'_id': ObjectId('629e14cacd42703bcd93e03b'), 'index': 1, 'name': 'Christopher Becker', 'age': 46, 'street': '171 Michelle Branch Apt. 253', 'city': 'Andrewton', 'state': 'Texas', 'zip': 77027, 'lng': -85.662816, 'lat': 87.893525}
{'_id': ObjectId('629e14cacd42703bcd93e03c'), 'index': 2, 'name': 'Joseph Delgado', 'age': 77, 'street': '771 Horne Ferry Suite 787', 'city': 'Mooretown', 'state': 'Idaho', 'zip': 46500, 'lng': -58.083436, 'lat': -28.560389}
{'_id': ObjectId('629e14cacd42703bcd93e03d'), 'index': 3, 'name': 'Justin Owens', 'age': 21, 'street': '242 Nicole Crossroad Apt. 208', 'city': 'East Omar', 'state': 'Missouri', 'zip': 5246, 'lng': -2.251244, 'lat': 14.322541}
{'_id': ObjectId('629e14cacd42703bcd93e03e'), 'index': 4, 'name': 'Robert Harris', 'age': 73, 'street': '5945 Cheryl Vista Suite 187', 'city': 'Jasonstad', 'state': 'Nevada', 'zip': 30805, 'lng': -166.650078, 'lat': -42.389466}
{'_id': ObjectId('629e14cacd42703bcd93e03f'), 'index': 5, 'name': 'Dr. Joseph Stokes PhD', 'age': 32, 'street': '04268 Gilbert Vista Suite 277', 'city': 'Ruizberg', 'state': 'Minnesota', 'zip': 17108, 'lng': 66.582027, 'lat': 61.055819}
{'_id': ObjectId('629e14cacd42703bcd93e040'), 'index': 6, 'name': 'Amanda Diaz', 'age': 55, 'street': '993 Lee Bypass Suite 744', 'city': 'Lake Angela', 'state': 'New Mexico', 'zip': 78195, 'lng': -82.284952, 'lat': -31.967741}
{'_id': ObjectId('629e14cacd42703bcd93e041'), 'index': 7, 'name': 'Jodi Randall', 'age': 44, 'street': '52154 William Greens Suite 765', 'city': 'Port Sharonstad', 'state': 'Alabama', 'zip': 49609, 'lng': -27.807087, 'lat': 28.7137065}
{'_id': ObjectId('629e14cacd42703bcd93e042'), 'index': 8, 'name': 'Amber Reid', 'age': 77, 'street': '4572 Stein Groves', 'city': 'Kruegerbury', 'state': 'Oregon', 'zip': 44020, 'lng': -80.733591, 'lat': -69.8993335}
{'_id': ObjectId('629e14cacd42703bcd93e043'), 'index': 9, 'name': 'Michael Webb', 'age': 32, 'street': '3197 Gabriela Camp Apt. 179', 'city': 'Harveyside', 'state': 'Nebraska', 'zip': 35633, 'lng': -72.490793, 'lat': -10.6487725}
{'_id': ObjectId('629e14cacd42703bcd93e044'), 'index': 10, 'name': 'Thomas Obrien', 'age': 48, 'street': '018 Trujillo Extensions', 'city': 'Vincentport', 'state': 'Wyoming', 'zip': 81424, 'lng': 41.910171, 'lat': 41.1628745}
{'_id': ObjectId('629e14cacd42703bcd93e045'), 'index': 11, 'name': 'Ronald Reed', 'age': 57, 'street': '4183 Eric Squares', 'city': 'Stephaniestad', 'state': 'Louisiana', 'zip': 54201, 'lng': 101.84359, 'lat': -18.42212}
{'_id': ObjectId('629e14cacd42703bcd93e046'), 'index': 12, 'name': 'Danielle Costa', 'age': 43, 'street': '94237 Mark Port Suite 151', 'city': 'Port Lindahaven', 'state': 'North Carolina', 'zip': 43086, 'lng': 173.765659, 'lat': -16.260263}
{'_id': ObjectId('629e14cacd42703bcd93e047'), 'index': 13, 'name': 'Danielle Mann', 'age': 68, 'street': '880 Rodriguez Summit Apt. 635', 'city': 'East Phyllis', 'state': 'Montana', 'zip': 19556, 'lng': 6.492303, 'lat': 20.5005165}
{'_id': ObjectId('629e14cacd42703bcd93e048'), 'index': 14, 'name': 'Tracy Lawson', 'age': 50, 'street': '8318 Brittany Hollow', 'city': 'North Justinton', 'state': 'South Dakota', 'zip': 82400, 'lng': 120.263544, 'lat': 75.855489}
{'_id': ObjectId('629e14cacd42703bcd93e049'), 'index': 15, 'name': 'Mary Jones', 'age': 58, 'street': '80137 Matthew Ridges Apt. 748', 'city': 'West Christopher', 'state': 'Arkansas', 'zip': 23130, 'lng': -99.079196, 'lat': 13.409937}
{'_id': ObjectId('629e14cacd42703bcd93e04a'), 'index': 16, 'name': 'Garrett Clark', 'age': 80, 'street': '668 Andrea Shoal Apt. 802', 'city': 'Moranville', 'state': 'Utah', 'zip': 42110, 'lng': -105.550391, 'lat': 85.2171955}
{'_id': ObjectId('629e14cacd42703bcd93e04b'), 'index': 17, 'name': 'Christina Brown', 'age': 35, 'street': '23131 James Plaza Suite 003', 'city': 'East Steve', 'state': 'Louisiana', 'zip': 86424, 'lng': 58.167224, 'lat': -81.164128}
{'_id': ObjectId('629e14cacd42703bcd93e04c'), 'index': 18, 'name': 'Jason Dudley', 'age': 69, 'street': '235 Ross Drives', 'city': 'Abbottchester', 'state': 'Tennessee', 'zip': 76952, 'lng': -46.277852, 'lat': -44.7627615}
{'_id': ObjectId('629e14cacd42703bcd93e04d'), 'index': 19, 'name': 'Shannon Gomez', 'age': 78, 'street': '30447 Brian Gardens', 'city': 'Katieton', 'state': 'Pennsylvania', 'zip': 59518, 'lng': -104.77913, 'lat': 79.6074115}
{'_id': ObjectId('629e14cacd42703bcd93e04e'), 'index': 20, 'name': 'John Glenn', 'age': 29, 'street': '41345 Laura Causeway Apt. 019', 'city': 'New Jacob', 'state': 'Florida', 'zip': 94007, 'lng': -67.911946, 'lat': -25.1018465}
{'_id': ObjectId('629e14cacd42703bcd93e04f'), 'index': 21, 'name': 'Martha Benson', 'age': 60, 'street': '15193 Anderson Glens', 'city': 'Port Jordanmouth', 'state': 'California', 'zip': 71510, 'lng': -73.197852, 'lat': 53.2857885}
{'_id': ObjectId('629e14cacd42703bcd93e050'), 'index': 22, 'name': 'Brandon Pham', 'age': 32, 'street': '7458 Hensley Lake Suite 491', 'city': 'Richardport', 'state': 'Wyoming', 'zip': 26972, 'lng': -137.504479, 'lat': 36.9539345}
{'_id': ObjectId('629e14cacd42703bcd93e051'), 'index': 23, 'name': 'Michael Zimmerman', 'age': 35, 'street': '9761 Felicia Mountain Apt. 893', 'city': 'Port Brittanymouth', 'state': 'Kansas', 'zip': 21157, 'lng': -131.696068, 'lat': -81.5647685}
{'_id': ObjectId('629e14cacd42703bcd93e052'), 'index': 24, 'name': 'Erika Sherman', 'age': 61, 'street': '64078 Anderson Trail', 'city': 'Phillipsshire', 'state': 'Pennsylvania', 'zip': 74916, 'lng': -22.683785, 'lat': -59.475196}
{'_id': ObjectId('629e14cacd42703bcd93e053'), 'index': 25, 'name': 'Cynthia Williams', 'age': 18, 'street': '204 Kirk Field', 'city': 'Ryanstad', 'state': 'South Dakota', 'zip': 82940, 'lng': 96.444636, 'lat': 79.716072}
{'_id': ObjectId('629e14cacd42703bcd93e054'), 'index': 26, 'name': 'Daniel Mitchell', 'age': 22, 'street': '36261 Elliott Hills', 'city': 'Kimchester', 'state': 'Minnesota', 'zip': 32631, 'lng': -28.437124, 'lat': -2.198261}
{'_id': ObjectId('629e14cacd42703bcd93e055'), 'index': 27, 'name': 'James Johnson', 'age': 65, 'street': '6244 Black Ridges', 'city': 'East Misty', 'state': 'Kentucky', 'zip': 77506, 'lng': 62.82673, 'lat': -3.808376}
{'_id': ObjectId('629e14cacd42703bcd93e056'), 'index': 28, 'name': 'Heather Day', 'age': 24, 'street': '59708 Brian Turnpike', 'city': 'Macktown', 'state': 'California', 'zip': 960, 'lng': -56.459241, 'lat': 31.3626945}
{'_id': ObjectId('629e14cacd42703bcd93e057'), 'index': 29, 'name': 'Manuel Hall', 'age': 52, 'street': '79806 Zoe Road Suite 809', 'city': 'Ruizhaven', 'state': 'North Dakota', 'zip': 87140, 'lng': 18.073795, 'lat': -59.9003285}
{'_id': ObjectId('629e14cacd42703bcd93e058'), 'index': 30, 'name': 'Marcus Williams', 'age': 46, 'street': '90990 Michael Drives Apt. 106', 'city': 'Michellefurt', 'state': 'Rhode Island', 'zip': 41753, 'lng': -139.616966, 'lat': 28.934036}
{'_id': ObjectId('629e14cacd42703bcd93e059'), 'index': 31, 'name': 'Mark Kirk', 'age': 59, 'street': '6890 Scott Trace', 'city': 'South Lynn', 'state': 'Arizona', 'zip': 32173, 'lng': -48.149025, 'lat': -70.1017965}
{'_id': ObjectId('629e14cacd42703bcd93e05a'), 'index': 32, 'name': 'Rodney Pierce', 'age': 39, 'street': '435 Eric Loaf', 'city': 'Christinaberg', 'state': 'Massachusetts', 'zip': 12744, 'lng': 171.270992, 'lat': 49.585763}
{'_id': ObjectId('629e14cacd42703bcd93e05b'), 'index': 33, 'name': 'Misty Montgomery', 'age': 75, 'street': '9146 Shawn Parks', 'city': 'Lake Jasonstad', 'state': 'Ohio', 'zip': 30879, 'lng': -71.354131, 'lat': 51.0863555}
{'_id': ObjectId('629e14cacd42703bcd93e05c'), 'index': 34, 'name': 'Jeffery Hunter', 'age': 23, 'street': '1933 Price Spurs Suite 997', 'city': 'South Jasonmouth', 'state': 'Kansas', 'zip': 87939, 'lng': -158.219113, 'lat': -83.3764825}
{'_id': ObjectId('629e14cacd42703bcd93e05d'), 'index': 35, 'name': 'Michael Savage', 'age': 37, 'street': '221 Keller Square Suite 667', 'city': 'South Brooke', 'state': 'Washington', 'zip': 93015, 'lng': 62.219691, 'lat': 34.1017655}
{'_id': ObjectId('629e14cacd42703bcd93e05e'), 'index': 36, 'name': 'John Clark', 'age': 57, 'street': '385 Patricia Harbors Suite 232', 'city': 'Mendeztown', 'state': 'Alaska', 'zip': 62284, 'lng': -40.94008, 'lat': -40.000225}
{'_id': ObjectId('629e14cacd42703bcd93e05f'), 'index': 37, 'name': 'David Snyder', 'age': 35, 'street': '323 Miller Ford', 'city': 'New Rodney', 'state': 'Pennsylvania', 'zip': 52516, 'lng': 67.998514, 'lat': 14.8724735}
{'_id': ObjectId('629e14cacd42703bcd93e060'), 'index': 38, 'name': 'Mary Berry', 'age': 66, 'street': '80847 Wolfe Flats Suite 355', 'city': 'South Aaron', 'state': 'Tennessee', 'zip': 6597, 'lng': 40.828649, 'lat': -73.029774}
{'_id': ObjectId('629e14cacd42703bcd93e061'), 'index': 39, 'name': 'Dana Miller', 'age': 57, 'street': '4004 Smith Parkways Apt. 731', 'city': 'South Megan', 'state': 'West Virginia', 'zip': 22441, 'lng': 112.411565, 'lat': -49.9677845}
{'_id': ObjectId('629e14cacd42703bcd93e062'), 'index': 40, 'name': 'Dr. William Allen', 'age': 57, 'street': '19482 Darrell Court Apt. 624', 'city': 'East Christinaton', 'state': 'New Hampshire', 'zip': 21082, 'lng': -29.549374, 'lat': 2.0372645}
{'_id': ObjectId('629e14cacd42703bcd93e063'), 'index': 41, 'name': 'James Rice', 'age': 59, 'street': '4042 Dawn Stravenue', 'city': 'Lake Elijahmouth', 'state': 'Delaware', 'zip': 95282, 'lng': 115.883605, 'lat': 46.829235}
{'_id': ObjectId('629e14cacd42703bcd93e064'), 'index': 42, 'name': 'Julie Hill', 'age': 66, 'street': '27413 Jonathan Brooks Suite 724', 'city': 'Tylerville', 'state': 'Vermont', 'zip': 3107, 'lng': 77.023998, 'lat': 50.530033}
{'_id': ObjectId('629e14cacd42703bcd93e065'), 'index': 43, 'name': 'Michael Deleon', 'age': 40, 'street': '1351 Moreno Flats', 'city': 'Baileyfort', 'state': 'Kentucky', 'zip': 91547, 'lng': -6.137088, 'lat': -20.774654}
{'_id': ObjectId('629e14cacd42703bcd93e066'), 'index': 44, 'name': 'Kevin Hernandez MD', 'age': 28, 'street': '45913 Burgess Corner', 'city': 'Port Allenland', 'state': 'Alabama', 'zip': 46128, 'lng': -126.601599, 'lat': -43.793205}
{'_id': ObjectId('629e14cacd42703bcd93e067'), 'index': 45, 'name': 'Amy Sellers', 'age': 26, 'street': '03040 Avery Branch Apt. 127', 'city': 'South Nicholas', 'state': 'Ohio', 'zip': 12696, 'lng': 178.564077, 'lat': 16.615402}
{'_id': ObjectId('629e14cacd42703bcd93e068'), 'index': 46, 'name': 'Steven Wright', 'age': 31, 'street': '5748 Herrera Estates', 'city': 'North Michaelfort', 'state': 'Missouri', 'zip': 45977, 'lng': -54.510026, 'lat': 40.6098555}
{'_id': ObjectId('629e14cacd42703bcd93e069'), 'index': 47, 'name': 'Sara White', 'age': 18, 'street': '4276 Richard Fords Apt. 393', 'city': 'Pricefurt', 'state': 'Alabama', 'zip': 91631, 'lng': -82.111421, 'lat': 67.710672}
{'_id': ObjectId('629e14cacd42703bcd93e06a'), 'index': 48, 'name': 'Lauren Brown', 'age': 42, 'street': '845 Stewart Mission Apt. 804', 'city': 'Lake Patriciashire', 'state': 'Missouri', 'zip': 62397, 'lng': -117.329294, 'lat': -70.1873895}
{'_id': ObjectId('629e14cacd42703bcd93e06b'), 'index': 49, 'name': 'Christopher Cobb', 'age': 68, 'street': '7323 Ayala Bypass Suite 496', 'city': 'Danielhaven', 'state': 'Wisconsin', 'zip': 41570, 'lng': 75.361101, 'lat': 69.158122}
{'_id': ObjectId('629e14cacd42703bcd93e06c'), 'index': 50, 'name': 'Martha Roy', 'age': 25, 'street': '715 Hurley Field', 'city': 'West Eugene', 'state': 'Connecticut', 'zip': 11643, 'lng': -48.782911, 'lat': 20.685614}
{'_id': ObjectId('629e14cacd42703bcd93e06d'), 'index': 51, 'name': 'Emily Rogers', 'age': 41, 'street': '729 Robert Rapids', 'city': 'Beckerville', 'state': 'Connecticut', 'zip': 15713, 'lng': -131.196701, 'lat': -3.414424}
{'_id': ObjectId('629e14cacd42703bcd93e06e'), 'index': 52, 'name': 'Jason Clark', 'age': 76, 'street': '03008 Sierra Mews Apt. 629', 'city': 'East Richardhaven', 'state': 'North Carolina', 'zip': 24254, 'lng': -69.854396, 'lat': -8.295709}
{'_id': ObjectId('629e14cacd42703bcd93e06f'), 'index': 53, 'name': 'Regina Turner', 'age': 36, 'street': '9459 Gardner Tunnel', 'city': 'Leeview', 'state': 'Michigan', 'zip': 28318, 'lng': -1.052019, 'lat': -33.7555645}
{'_id': ObjectId('629e14cacd42703bcd93e070'), 'index': 54, 'name': 'Holly Jackson', 'age': 31, 'street': '29749 Summers Dale', 'city': 'West Mary', 'state': 'Delaware', 'zip': 81416, 'lng': 137.792426, 'lat': 17.433021}
{'_id': ObjectId('629e14cacd42703bcd93e071'), 'index': 55, 'name': 'Traci Garcia', 'age': 30, 'street': '359 Mason Glen Suite 069', 'city': 'Lake Laura', 'state': 'Alabama', 'zip': 34530, 'lng': 72.144471, 'lat': 86.457872}
{'_id': ObjectId('629e14cacd42703bcd93e072'), 'index': 56, 'name': 'Shari Cole', 'age': 57, 'street': '268 Erika Lights', 'city': 'South Brian', 'state': 'Pennsylvania', 'zip': 43443, 'lng': 84.205356, 'lat': 69.776999}
{'_id': ObjectId('629e14cacd42703bcd93e073'), 'index': 57, 'name': 'Miss Barbara Gonzalez', 'age': 78, 'street': '26891 Barton Keys Apt. 503', 'city': 'Jacobmouth', 'state': 'Arkansas', 'zip': 29941, 'lng': 51.016196, 'lat': 52.0424745}
{'_id': ObjectId('629e14cacd42703bcd93e074'), 'index': 58, 'name': 'Bradley Sanchez', 'age': 38, 'street': '69138 Mary Falls', 'city': 'Taylorland', 'state': 'Georgia', 'zip': 98781, 'lng': 74.114628, 'lat': 57.1093555}
{'_id': ObjectId('629e14cacd42703bcd93e075'), 'index': 59, 'name': 'Robert Lee', 'age': 56, 'street': '621 Cummings Lock Suite 713', 'city': 'New Lee', 'state': 'Massachusetts', 'zip': 22411, 'lng': -23.339864, 'lat': -31.590373}
{'_id': ObjectId('629e14cacd42703bcd93e076'), 'index': 60, 'name': 'Terri Craig', 'age': 27, 'street': '70828 Marc Plains Apt. 360', 'city': 'Edwardsberg', 'state': 'Kentucky', 'zip': 70773, 'lng': 71.735611, 'lat': 84.181728}
{'_id': ObjectId('629e14cacd42703bcd93e077'), 'index': 61, 'name': 'Sarah Wilson', 'age': 40, 'street': '78160 Patricia Mount Apt. 904', 'city': 'Smithland', 'state': 'Connecticut', 'zip': 19078, 'lng': 146.130763, 'lat': 78.6517895}
{'_id': ObjectId('629e14cacd42703bcd93e078'), 'index': 62, 'name': 'Curtis Smith', 'age': 34, 'street': '44671 Taylor Meadows Suite 159', 'city': 'Lake Erictown', 'state': 'Nebraska', 'zip': 27347, 'lng': -36.218056, 'lat': 65.793745}
{'_id': ObjectId('629e14cacd42703bcd93e079'), 'index': 63, 'name': 'Christine Bowers', 'age': 39, 'street': '342 Rodriguez Well', 'city': 'North Michael', 'state': 'Nevada', 'zip': 54248, 'lng': -174.726988, 'lat': -4.106421}
{'_id': ObjectId('629e14cacd42703bcd93e07a'), 'index': 64, 'name': 'Scott Holland', 'age': 77, 'street': '6465 Sean Tunnel', 'city': 'Carmenview', 'state': 'Alaska', 'zip': 9224, 'lng': 84.865136, 'lat': -22.6048725}
{'_id': ObjectId('629e14cacd42703bcd93e07b'), 'index': 65, 'name': 'Jason Ellis', 'age': 31, 'street': '15228 Tyler Groves', 'city': 'Lake Jonathanton', 'state': 'Oregon', 'zip': 79850, 'lng': -120.927286, 'lat': -44.171071}
{'_id': ObjectId('629e14cacd42703bcd93e07c'), 'index': 66, 'name': 'Mark Davis', 'age': 62, 'street': '710 Chandler Flat Apt. 640', 'city': 'Jordanbury', 'state': 'Idaho', 'zip': 86909, 'lng': 171.4912, 'lat': -82.6735195}
{'_id': ObjectId('629e14cacd42703bcd93e07d'), 'index': 67, 'name': 'James Barnes', 'age': 50, 'street': '53825 Avery Glens', 'city': 'Lake Catherineberg', 'state': 'Tennessee', 'zip': 21370, 'lng': -33.879651, 'lat': -17.1380575}
{'_id': ObjectId('629e14cacd42703bcd93e07e'), 'index': 68, 'name': 'Kelsey Nelson', 'age': 42, 'street': '64224 Derrick Fall Apt. 555', 'city': 'Turnerborough', 'state': 'Indiana', 'zip': 63467, 'lng': 48.758038, 'lat': -21.0923035}
{'_id': ObjectId('629e14cacd42703bcd93e07f'), 'index': 69, 'name': 'Jonathan Horne', 'age': 43, 'street': '557 James Meadow', 'city': 'Lake Thomas', 'state': 'Wisconsin', 'zip': 84680, 'lng': 54.619491, 'lat': -85.12731}
{'_id': ObjectId('629e14cacd42703bcd93e080'), 'index': 70, 'name': 'Tammy Yang', 'age': 35, 'street': '744 Olsen Motorway Suite 277', 'city': 'Wendyfort', 'state': 'North Carolina', 'zip': 40732, 'lng': 167.876536, 'lat': 88.9626775}
{'_id': ObjectId('629e14cacd42703bcd93e081'), 'index': 71, 'name': 'David Gonzalez', 'age': 59, 'street': '15509 Anna Trafficway Suite 211', 'city': 'Perryton', 'state': 'Maryland', 'zip': 16615, 'lng': 131.277969, 'lat': 38.7011905}
{'_id': ObjectId('629e14cacd42703bcd93e082'), 'index': 72, 'name': 'Lauren Thomas', 'age': 75, 'street': '213 Mcneil Common', 'city': 'Port Donna', 'state': 'Rhode Island', 'zip': 73032, 'lng': -18.078895, 'lat': 68.1240045}
{'_id': ObjectId('629e14cacd42703bcd93e083'), 'index': 73, 'name': 'Andrew Fox', 'age': 19, 'street': '2804 Timothy Garden', 'city': 'Toddborough', 'state': 'West Virginia', 'zip': 10126, 'lng': 46.723058, 'lat': -67.468115}
{'_id': ObjectId('629e14cacd42703bcd93e084'), 'index': 74, 'name': 'Jason Weeks', 'age': 67, 'street': '2025 White Mill', 'city': 'New Jennifer', 'state': 'New Hampshire', 'zip': 48085, 'lng': 124.969467, 'lat': -56.464533}
{'_id': ObjectId('629e14cacd42703bcd93e085'), 'index': 75, 'name': 'Steven Terrell', 'age': 27, 'street': '8610 Gary Wells Suite 560', 'city': 'East Kimberlyport', 'state': 'New York', 'zip': 89064, 'lng': -143.27752, 'lat': -40.456603}
{'_id': ObjectId('629e14cacd42703bcd93e086'), 'index': 76, 'name': 'Jeffery Melendez', 'age': 62, 'street': '642 Kevin Freeway', 'city': 'Michaelville', 'state': 'Kentucky', 'zip': 7355, 'lng': 123.699735, 'lat': 26.328674}
{'_id': ObjectId('629e14cacd42703bcd93e087'), 'index': 77, 'name': 'Kathryn Baker', 'age': 67, 'street': '471 Gonzalez Ways', 'city': 'Lake Sarahfort', 'state': 'Arizona', 'zip': 84147, 'lng': -149.507483, 'lat': 41.5379945}
{'_id': ObjectId('629e14cacd42703bcd93e088'), 'index': 78, 'name': 'Sharon Griffin', 'age': 60, 'street': '40808 Matthews Trafficway', 'city': 'Choitown', 'state': 'South Dakota', 'zip': 48227, 'lng': 47.190669, 'lat': 75.097}
{'_id': ObjectId('629e14cacd42703bcd93e089'), 'index': 79, 'name': 'Samantha Miller', 'age': 24, 'street': '2880 Nathan Ridges Suite 730', 'city': 'South Robertfort', 'state': 'North Carolina', 'zip': 55229, 'lng': 38.095331, 'lat': 41.872883}
{'_id': ObjectId('629e14cacd42703bcd93e08a'), 'index': 80, 'name': 'Mr. Jon Nelson MD', 'age': 52, 'street': '646 Anna Meadows Apt. 400', 'city': 'West Rhondafurt', 'state': 'Oregon', 'zip': 1467, 'lng': 86.114153, 'lat': 24.1575725}
{'_id': ObjectId('629e14cacd42703bcd93e08b'), 'index': 81, 'name': 'Jorge Ferguson', 'age': 52, 'street': '5467 Michael Keys', 'city': 'South Sarahmouth', 'state': 'Delaware', 'zip': 98894, 'lng': 90.919653, 'lat': 37.3384215}
{'_id': ObjectId('629e14cacd42703bcd93e08c'), 'index': 82, 'name': 'Leonard Brown', 'age': 58, 'street': '00688 Robert Fields Suite 088', 'city': 'Washingtonmouth', 'state': 'Idaho', 'zip': 80654, 'lng': 27.349573, 'lat': -85.499879}
{'_id': ObjectId('629e14cacd42703bcd93e08d'), 'index': 83, 'name': 'Katelyn Williams', 'age': 76, 'street': '494 Michael Harbors Apt. 631', 'city': 'Port Darryl', 'state': 'Florida', 'zip': 5020, 'lng': -39.997027, 'lat': -5.790753}
{'_id': ObjectId('629e14cacd42703bcd93e08e'), 'index': 84, 'name': 'Walter Rodriguez', 'age': 38, 'street': '8611 Brown Forge Apt. 270', 'city': 'Ashleymouth', 'state': 'Wisconsin', 'zip': 97652, 'lng': -131.485398, 'lat': 20.680008}
{'_id': ObjectId('629e14cacd42703bcd93e08f'), 'index': 85, 'name': 'William Williams', 'age': 31, 'street': '6218 Benjamin Centers Apt. 982', 'city': 'Darrenton', 'state': 'Indiana', 'zip': 36953, 'lng': -123.417715, 'lat': -78.7012495}
{'_id': ObjectId('629e14cacd42703bcd93e090'), 'index': 86, 'name': 'Melissa Wright', 'age': 31, 'street': '702 Karen Track', 'city': 'Angelaborough', 'state': 'Missouri', 'zip': 74745, 'lng': 112.221869, 'lat': -1.754663}